### ISSUE TITLE
Update blobs to 1.20.1 version

### ISSUE THREAD

**Issue by borodust** [borodust/bodge-openal#2]
Looks like 1.19.1 having problems on macos at the moment. It consumes the whole CPU core after initializing a context. 1.20.1 doesn't seem to have this problem.

**Comment by borodust** [comment]
Done. In testing dist soon.

**Comment by svetlyak40wt** [comment]
Great!

How can I install a testing dist?

**Comment by borodust** [comment]
```
(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.testing.txt")
```
No need to remove stable dist.

**Comment by svetlyak40wt** [comment]
Today I've checked the test dist 2020041217123.

The problem is gone. Now my app eats only about 17-20% CPU.
